export const copy = {
  en: {
    title: 'Keep your orbit.',
    subtitle: 'Outlast the meteor shower.',
    description:
      'Gravity pulls. Momentum carries.\nTurn your ship. Tap your thrusters. Stay alive.',
    launch: 'Enter orbit',
    again: 'Fly again',
    pause: 'Flight paused',
    pauseText: 'A quiet moment in the cosmos.\nContinue when you’re ready.',
    resume: 'Continue flight',
    over: 'One more orbit?',
    loading: 'Receiving star map…',
    failed: 'Star map unavailable',
    retry: 'Retry loading',
    ready: 'READY FOR FLIGHT',
    playing: 'IN ORBIT',
    paused: 'PAUSED',
    ended: 'SIGNAL LOST',
    time: 'SURVIVAL TIME',
    best: 'Personal best',
    thisFlight: 'This flight',
    guide: 'Flight path',
    mute: 'Mute audio',
    unmute: 'Unmute audio',
    settings: 'Settings',
    close: 'Close',
    controls: 'How to play',
    credits: 'Credits',
    music: 'Music',
    effects: 'Sound effects',
    muted: 'All audio muted',
    audioNote: 'Audio begins after you enter orbit.',
    audioUnavailable: 'Some audio is unavailable. You can still play.',
    audioLoading: 'Audio will load when you start.',
    pauseNote: 'Press P or Space to continue',
    replayNote: 'Press R to fly again',
    launchNote: 'First challenge: survive 30 seconds.',
    turn: 'Turn',
    thrust: 'Thrust',
    stop: 'Pause',
    restart: 'Restart',
    speed: 'Speed',
    altitude: 'Altitude',
    engine: 'Thrusters',
    on: 'FIRING',
    off: 'IDLE',
    telemetry: 'FLIGHT TELEMETRY',
    advice: 'Short burns. Small corrections.',
    setup: 'Turning changes your heading, not your momentum.',
    gravity: 'GRAVITY LOCKED',
    planet: 'Planetary gravity · always on',
    planetDeath: 'You hit the planet. Turn away from the surface and use a short burst of thrust.',
    boundaryDeath:
      'You left the flight zone. Turn toward the planet and gently adjust your course.',
    asteroidDeath: 'A meteor found you. Watch its trail and use a short burn to change your path.',
    planetWarning: 'Surface approaching · thrust outward',
    boundaryWarning: 'Flight boundary · adjust your course',
    step1: 'Turn your ship',
    detail1:
      'Use ← / → or A / D to point the nose. Turning alone does not change your flight path.',
    step2: 'Tap, don’t hold',
    detail2: 'Use ↑ or W for short bursts of thrust. You already start with enough speed to orbit.',
    step3: 'Stay in the flight zone',
    detail3:
      'Avoid the planet, meteors, and the dotted edge. Survive as long as you can; press R to try again.',
    touch:
      'On touchscreens, hold the left / right arrows and tap THRUST. Two fingers work together.',
    background: 'Switching tabs pauses your flight and audio. Resume when you return.',
    fullscreen: 'Enter fullscreen',
    fullscreenFail: 'Fullscreen is unavailable here. Use the host page’s fullscreen button.',
    language: 'Language',
    local: 'Your best time and preferences stay in this browser. No account needed.',
    attribution: 'Music and sound effects',
    art: 'Space artwork created with AI image generation. Physics, interface, and game assembled with AI assistance.',
    musicCredit:
      'Music: “Outer Space Loop” by wipics. Trimmed, loop crossfaded, and level adjusted.',
    effectsCredit:
      'Sound effects: Sci-fi Sounds and Interface Sounds by Kenney. Converted and loop edited.',
    license: 'Audio licensed under CC0 1.0.',
  },
  zh: {
    title: '保持轨道。',
    subtitle: '躲过下一颗陨石。',
    description: '引力牵引你，惯性带着你。\n转动船头，轻点推进，在陨石雨中活得更久。',
    launch: '进入轨道',
    again: '再次出发',
    pause: '让宇宙等一会儿。',
    pauseText: '你的飞船已停在这一刻。\n准备好了就继续。',
    resume: '继续飞行',
    over: '再试一次轨道。',
    loading: '正在接收星图…',
    failed: '素材未能加载',
    retry: '重新加载',
    ready: '飞行准备就绪',
    playing: '飞行中',
    paused: '飞行已暂停',
    ended: '信号中断',
    time: '生存时间',
    best: '本机最佳',
    thisFlight: '本次飞行',
    guide: '轨迹辅助',
    mute: '静音',
    unmute: '开启声音',
    settings: '设置',
    close: '关闭',
    controls: '操作指南',
    credits: '制作与署名',
    music: '背景音乐',
    effects: '音效',
    muted: '全部声音已静音',
    audioNote: '进入轨道后，音乐与音效开始播放。',
    audioUnavailable: '部分声音暂不可用，仍可正常游玩。',
    audioLoading: '开始飞行后加载声音。',
    pauseNote: '按 P 或空格继续',
    replayNote: '按 R 再次出发',
    launchNote: '第一个挑战：坚持 30 秒。',
    turn: '转向',
    thrust: '推进',
    stop: '暂停',
    restart: '重来',
    speed: '相对速度',
    altitude: '地表高度',
    engine: '推进器',
    on: '点火中',
    off: '待命',
    telemetry: '飞行遥测',
    advice: '小幅推进，更容易维持轨道。',
    setup: '推进改变速度，转向改变朝向。',
    gravity: '引力场已锁定',
    planet: '行星引力 · 持续生效',
    planetDeath: '飞船撞上了星球。提前转向，朝远离地表的方向轻点推进。',
    boundaryDeath: '飞船飞出了画面边界。试着把船头转向星球，轻点推进。',
    asteroidDeath: '飞船被陨石击中了。留意陨石的尾迹，用短促推进改变航线。',
    planetWarning: '正在接近地表 · 向外推进',
    boundaryWarning: '正在接近边界 · 调整航向',
    step1: '先转动船头',
    detail1: '按 ← / → 或 A / D 转向。转向只改变朝向，不会立刻改变飞行方向。',
    step2: '轻点推进，别一直按',
    detail2: '按 ↑ 或 W 点火。起飞时已具备环绕速度，短促推进即可调整轨道。',
    step3: '留在飞行区域内',
    detail3: '避开星球、陨石和画面边缘的虚线，坚持得越久越好。按 R 可以重新开始。',
    touch: '触屏：按住左／右箭头转向，轻点“推进”。可同时用两根手指操作。',
    background: '切换标签页会暂停飞行和声音，回来后主动继续。',
    fullscreen: '进入全屏',
    fullscreenFail: '当前环境无法进入全屏，可使用平台页面的全屏按钮。',
    language: '语言',
    local: '最高纪录和偏好保存在当前浏览器，无需账号。',
    attribution: '音乐与音效',
    art: '太空美术使用 AI 图像生成；物理、界面与游戏由 AI 辅助制作。',
    musicCredit: '音乐：“Outer Space Loop”，作者 wipics。做了裁剪、循环交叉淡化和音量调整。',
    effectsCredit: '音效：Kenney 的 Sci-fi Sounds 与 Interface Sounds。做了格式转换和循环编辑。',
    license: '音频采用 CC0 1.0 许可。',
  },
};
