export const growthCopy = {
  en: {
    next: 'Next target',
    all: 'All stages reached',
    reached: 'Stage reached',
    record: 'New personal best!',
    stages: 'Stages',
    none: 'Keep going — 30s is the first target.',
    share: 'Share flight',
    preparing: 'Preparing your PNG…',
    download: 'Download PNG',
    system: 'System share',
    link: 'Copy game link',
    noLink: 'The public game link is not configured yet. Your PNG is ready to keep.',
    cardError: 'Could not create the image. Close and try again.',
    complete: 'Share action completed. This does not confirm a recipient opened it.',
    cancel: 'Share dismissed or no target available. Nothing was confirmed.',
    fallback: 'System share is unavailable here. Download the PNG or copy the link.',
    copied: 'Link copied.',
    copyError: 'Clipboard unavailable. Select and copy the link below.',
    downloaded: 'PNG download requested. You can also save the preview image.',
    privacy: 'Data & privacy',
    privacyText:
      'When enabled, anonymous flight events, campaign labels and time counters go to the game operator. No email, typed text, fingerprint or full referring URL is collected. Events are retained for 90 days. Pending events retry for up to 7 days. Turn off to stop collection and remove this browser’s analytics ID and queue. Already received data remains until expiry.',
    tracking: 'Allow anonymous play statistics',
    disabled: 'Collection is not configured in this build.',
    active: 'Anonymous play statistics are enabled.',
    off: 'Anonymous play statistics are off.',
    test: 'This is a local/test session; excluded from production totals.',
    local: 'Best time, language and audio preferences remain on this device.',
    openGame: 'Official game page',
    fair: 'Personal record; screen size affects play.',
    referralNote:
      'A copied itch.io page link may not pass its campaign into the game. Attributed visits require the configured direct play link.',
  },
  zh: {
    next: '下一目标',
    all: '全部阶段已达成',
    reached: '阶段达成',
    record: '刷新本机纪录！',
    stages: '达成阶段',
    none: '继续尝试，30 秒是第一个目标。',
    share: '分享本次飞行',
    preparing: '正在生成 PNG…',
    download: '下载 PNG',
    system: '系统分享',
    link: '复制游戏链接',
    noLink: '正式游戏链接尚未配置，可以先保存这张 PNG 成绩卡。',
    cardError: '图片生成失败，请关闭后重试。',
    complete: '系统分享操作已完成，不代表对方已打开。',
    cancel: '分享已取消，或系统没有可用目标；未确认分享完成。',
    fallback: '此环境无法系统分享，请下载 PNG 或复制链接。',
    copied: '链接已复制。',
    copyError: '剪贴板不可用，请选中下方链接手动复制。',
    downloaded: '已请求下载 PNG，也可以保存预览图片。',
    privacy: '数据与隐私',
    privacyText:
      '启用后，匿名飞行事件、渠道标签和计时会发送给游戏运营者。不收集邮箱、输入内容、设备指纹或完整来源网址。事件保留 90 天，待发送事件最多重试 7 天。关闭会停止采集并清除此浏览器的分析标识与队列；已接收数据到期清理。',
    tracking: '允许匿名游玩统计',
    disabled: '此版本尚未配置数据接收服务。',
    active: '匿名游玩统计已开启。',
    off: '匿名游玩统计已关闭。',
    test: '当前是本地／测试会话，不计入正式数据。',
    local: '最高纪录、语言和音量偏好继续保存在本机。',
    openGame: '正式游戏页面',
    fair: '本机飞行记录；屏幕尺寸会影响玩法。',
    referralNote: 'itch.io 页面链接的渠道参数未必能传入游戏；精确推荐归因需要配置独立试玩链接。',
  },
};
